version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
  
  frontend:
    build:
      context: ./frontend
    container_name: streamlit-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
