version: '3.8'

services:
  backend:
    build: ./backend
    container_name: budget_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - budget_net

  frontend:
    build: ./frontend
    container_name: budget_frontend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - budget_net
    environment:
      - BACKEND_URL=http://backend:8000

networks:
  budget_net:
    driver: bridge
